---
- hosts: raspberry

  tasks:

    - name: "Install dependencies required for python packages"
      become: yes
      apt:
        name: ["python-setuptools",
               "python3-setuptools",
               "python3-numpy",
               "libblas-dev",
               "liblapack-dev",
               "python3-dev",
               "libatlas-base-dev",
               "gfortran",
               "python3-scipy",
               "python3-dev",
               "python3-pip"]
        update_cache: yes

    - name: Clean artifact path
      file:
        state: absent
        path: "/tmp/tensorflow-1.12.0-cp35-none-linux_armv7l.whl"

    - name: "Retrieve Tensorflow on ARM wheel"
      get_url:
        url: "https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.12.0/tensorflow-1.12.0-cp35-none-linux_armv7l.whl"
        dest: "/tmp"

    - name: "Install tensorflow package using wheel"
      become: yes
      pip:
        name: "file:///tmp/tensorflow-1.12.0-cp35-none-linux_armv7l.whl"
        executable: /usr/bin/pip3

    - name: "Install additional dependencies required for keras packages (sequential dependencies)"
      become: yes
      apt:
        name: python3-h5py


    - name: "Install keras package"
      become: yes
      pip:
        name: keras
        executable: /usr/bin/pip3
        version: 2.2.4


    - name: "Install Pillow package"
      become: yes
      pip:
        name: pillow
        executable: /usr/bin/pip3
